
#路径 D:\application\anaconda3\envs\dixiLOG\Lib\site-packages\material\templates

# 项目信息
# 站点作者
site_author: dixi  
# 站名
site_name: dixi's BLOG
# 站点地址
# site_url: https://localhost:8000/
site_url: https://dixilog.github.io/

site_description: >- # 项目描述
  Welcome to dixi's BLOG. Ad infinitum, ad aeternum progredi.
# 代码仓库信息
repo_name:  dixiLOG # 仓库名称
repo_url: https://github.com/dixiLOG/dixiLOG.github.io.git # 仓库地址
# 版权信息
copyright: Copyright &copy; 2024 | powered by dixiLOG | All rights reserved.
# 导航树配置
nav:
  - Home: 
    - index.md
    - Build Your Own Blog: 
      - build_your_web/index.md
      - build_your_web/access your github.io.md
      - build_your_web/玩转 Material.md
      - build_your_web/feishu2githubPages.md
    - build_your_web/markdown 速记.md
  - NBU-NOTEBOOK: 
      - NBU-NOTEBOOK/index.md
      - 信号与系统笔记 :
        - NBU-NOTEBOOK/S&S/index.md
        - NBU-NOTEBOOK/S&S/S&S01.md
        - NBU-NOTEBOOK/S&S/S&S02.md
        - NBU-NOTEBOOK/S&S/S&S03.md
        - NBU-NOTEBOOK/S&S/S&S04.md
        - NBU-NOTEBOOK/S&S/S&S05.md
        - NBU-NOTEBOOK/S&S/S&S06.md

  - 随手记:
      - 随手记/index.md
      - 无聊可期:
        - 随手记/boringBetter/index.md
        - 随手记/boringBetter/reallyStars.md
        - 随手记/boringBetter/awesomeFinds.md
        - 随手记/boringBetter/shoddyGoods.md
      - 十万个为什么:
        - 随手记/whywhy/index.md
        - 随手记/whywhy/huangli.md
        - 随手记/whywhy/runningGap.md
  - 长河集:
      - changheji/index.md
      - 荒唐言:
        - changheji/bookReport/index.md
        - changheji/bookReport/《鄙视》阅读报告.md
        - changheji/bookReport/《华尔街日报是如何讲故事的》阅读报告.md
        - changheji/bookReport/《文心雕龙》摘抄本.md
        - changheji/bookReport/《远大前程》阅读报告.md
  - NBU_ROCOS:
      - ROCOS/index.md
      - ROCOS/info&ref.md
  - 闲言碎语:
      - blog/index.md

# 主题配置
theme:
  name: material # 主题名称
  # custom_dir: material/overrides # 自定义文件夹，对于个别页面，如果你不想使用主题的默认样式，可以在这里进行修改，使用里面的文件覆盖主题的默认文件。具体可以参考material官方文档。
  # logo: static/images/logo.png # logo 图片  
  logo: https://cdn.jsdelivr.net/gh/dixiLOG/blogStatic/%E4%B8%AA%E4%BA%BA%E5%A4%B4%E5%83%8F_4x.png # logo 图片  
  favicon: img/favicon.ico  # 网站图标
  language: zh # 语言
  font: # 字体，大概率不需要换
    text: Roboto
    code: Roboto Mono
  palette:
  - media: "(prefers-color-scheme: light)" # 浅色
    scheme: default
    primary: light green
    accent: orange
    toggle:
      icon: material/lightbulb-variant
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)" # 深色
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-variant-outline
      name: Switch to light mode
  icon: # 一些用到的icon
    logo: logo
    previous: material/skip-previous
    next: material/skip-next
    repo: fontawesome/brands/git-alt 
    annotation: material/chevron-right-circle
    search: material/text-box-search
    close: material/close-box-outline
  # 功能
  features:
    # - header.autohide # 自动隐藏头部
    - navigation.instant # 导航栏快速跳转
    - navigation.tabs # 导航栏多标签
    # - navigation.sections # 开启后左侧导航栏不折叠
    - navigation.tracking # 导航栏URL跟踪
    - navigation.footer # 底部导航栏
    - search.highlight # 搜索结果高亮
    # - navigation.expand # 导航栏展开
    - navigation.indexes # 提供概述页面
    - navigation.prune # 导航栏修剪
    - toc.follow # 目录跟随
    # - navigation.tabs # 顶级索引被作为tab
    # - navigation.tabs.sticky # 导航栏始终可见
    # - toc.integrate # 目录集成左边栏
    - navigation.top # 快速回到顶部
    - content.code.annotate # 代码注解
    - content.tooltips # 工具提示
    - search.suggest # 搜索建议
    - search.share # 搜索结果分享
    - content.code.copy # 复制代码按钮
    # - navigation.instant.prefetch # 预加载
    # - navigation.instant.progress # 进度条

# 插件配置
plugins:
- search: # 搜索
    lang: 
      - en
      - zh  # 中文搜索支持
- tags # 标签功能 插件
- glightbox: # 图片灯箱
    skip_classes:
         - custom-skip-class-name
# - meta-descriptions:
#     export_csv: false
#     quiet: false
#     enable_checks: false
#     min_length: 50
#     max_length: 160
#     trim: false # 元描述插件
- statistics: # 统计功能插件
    page_template: "page_template/page_statistics.html"
    words_per_minute: 180
- blog: # 博客功能插件
    blog_dir: blog
    # blog_toc: true
    post_date_format: full
    archive_toc: true
    categories_toc: true
    archive_name: DIXI的碎碎念流水
    # archive_date_format: MMMM
    category_name: DIXI的碎碎念分类
    # categories_allowed:      # 允许的分类
      # - 口水鸡  #书 电影
      # - 豆腐脑  #输出观点
      # - 碎碎念  #随笔
    pagination_per_page: 15 # 每页文章数
    # post_excerpt: required # 文章摘要,和下面的配合食用，但不知道为什么我不能开启这一句
    post_excerpt_separator: <!-- more -->
    pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"   # 页码格式
    # pagination_keep_content: true   # 保留分页内容
    # draft_if_future_date: true # 草稿发布日期大于当前日期则发布为草稿
    post_readtime: false   # 关闭阅读时间
    # post_readtime_words_per_minute: 300
# - print-site: # 打印功能插件
- git-revision-date-localized:  # 日期插件
    enabled: true
    fallback_to_build_date: true
    enable_creation_date: true  # 显示创建时间
    type: iso_datetime               # 日期显示格式（如 "2周前"）
    # custom_format: "%Y-%m-%d"   # 自定义日期格式（如 "2023-10-01"）
    locale: zh                  # 本地化语言（中文）
    timezone: Asia/Shanghai     # 时区
    exclude:                    # 排除某些文件
    - index.md


# mk扩展配置
markdown_extensions:
  - toc:      # 目录
      permalink: true
      toc_depth: 4
      title: Contents
  # - meta
  - abbr
  - tables
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark #支持高亮标记文本。
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - markdown.extensions.attr_list
  - pymdownx.smartsymbols
  - pymdownx.arithmatex
  - pymdownx.caret
  - footnotes
  
  - pymdownx.betterem:     # 改进的强调
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:      # 标签页
      alternate_style: true 
  - pymdownx.tasklist:    # 任务列表
      custom_checkbox: true
  - pymdownx.highlight:    # 代码高亮
      anchor_linenums: true
  - pymdownx.arithmatex:  # 数学公式
      generic: true
  - pymdownx.superfences:    # diagrams | 流程图
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

# 其他配置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dixiLOG
      name: 我滴GitHub
  analytics:
    provider: google
    property: G-WNP42HF8NE
    feedback:
      title: Looking for your feedback!
      ratings:
        - icon: material/thumb-up-outline 
          name: This page was helpful
          data: 1
          note: >-
           O(∩_∩)O谢谢啦~
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            嘿呀嘿呀，努力搬砖...

# 额外的模板文件
extra_templates:
  - 404.html  # 404页面模板

# 额外的js文件和css文件
extra_javascript:
  # 自定义js文件，一定要放在最后面，不然会覆盖掉主题的js文件
  # - https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js   
  # - https://www.gstatic.com/firebasejs/8.10.0/firebase-auth.js
  - javascripts/extra.js
  - https://imgbb.com/upload.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

  # - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://unpkg.com/katex@0/dist/katex.min.css
