authors:
    dixi:
        name: dixi        # Author name
        description: 略略略😋 # Author description
        avatar: https://cdn.jsdelivr.net/gh/dixiLOG/blogStatic/%E4%B8%AA%E4%BA%BA%E5%A4%B4%E5%83%8F.png # Author avatar