name: publish site
on: # 在什么时候触发工作流
  push: # 在从本地main分支被push到GitHub仓库时
    branches:
      - main
  pull_request: # 在main分支合并别人提的pr时
    branches:
      - main
jobs: # 工作流的具体内容
  deploy:
    runs-on: ubuntu-latest # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    steps:
      - uses: actions/checkout@v4 # 先checkout到main分支
        with:
            fetch-depth: 0

      - uses: actions/setup-python@v4 # 再安装Python3和相关环境
        with:
          python-version: 3.x

      # 使用 GitHub Actions 部署，需在配置文件中添加插件安装步骤：不加则github编译报错
      - run: pip install mkdocs-material # 使用pip包管理工具安装mkdocs-material
      - run: pip install mkdocs-statistics-plugin
      - run: pip install mkdocs-rss-plugin # 附加rss插件
      - run: pip install mkdocs-print-site-plugin # 附加打印插件
      - run: pip install mkdocs-glightbox # 附加图片放大插件
      - run: pip install mkdocs-git-revision-date-localized-plugin # 日期记录
      - run: pip install mkdocs-pdf

      # 手动添加一个步骤来配置 Git 的用户信息
      - name: Configure Git
        run: |
          git config --global user.name "dixiLOG"
          git config --global user.email "1444127184@qq.com"
      # 编译网站，最后再run
      - run: mkdocs gh-deploy --force # 使用mkdocs-material部署gh-pages分支
